spring:
  datasource:
    url: jdbc:mysql://localhost:3306/exam5?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: utf-8

  mvc:
    hiddenmethod:
      filter:
        enabled: true


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.qssy.exam.webexam.entity

# pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
server:
  port: 8444